# Generated by Django 5.0.2 on 2024-03-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserImage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='DOB',
        ),
    ]
