# Generated by Django 5.0.2 on 2024-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserImage', '0006_alter_user_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_field',
            field=models.ImageField(blank=True, max_length=20000, null=True, upload_to='Image'),
        ),
    ]
